/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswerBar: typeof import('./src/components/AnswerBar.vue')['default']
    MemoryCurve: typeof import('./src/components/MemoryCurve.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WordCard: typeof import('./src/components/WordCard.vue')['default']
  }
}
